FROM istepanov/dokuwiki
WORKDIR /var/dokuwiki-storage/

RUN apk --update add php7-json && rm -rf /var/cache/apk/*

RUN  rm -rf /var/www/lib/plugins/ && \
     ln -s /var/dokuwiki-storage/lib/plugins /var/www/lib/plugins && \
     rm -rf /var/www/lib/styles/ && \
     ln -s /var/dokuwiki-storage/lib/styles /var/www/lib/styles && \
     rm -rf /var/www/lib/tpl/ && \
     ln -s /var/dokuwiki-storage/lib/tpl /var/www/lib/tpl
