FROM istepanov/dokuwiki
WORKDIR /var/dokuwiki-storage/

RUN apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add \
    php7-json php7-curl php7-bcmath php7-mcrypt php7-openssl php7-zip && rm -rf /var/cache/apk/*
    
RUN  rm -rf /var/www/lib/plugins/ && \
     ln -s /var/dokuwiki-storage/lib/plugins /var/www/lib/plugins && \
     rm -rf /var/www/lib/styles/ && \
     ln -s /var/dokuwiki-storage/lib/styles /var/www/lib/styles && \
     rm -rf /var/www/lib/tpl/ && \
     ln -s /var/dokuwiki-storage/lib/tpl /var/www/lib/tpl
